.Dd $Mdocdate$
.Dt shat 1
.Os
.Sh NAME
.Nm shat
.Nd cheesy, neutered Haskell implementation of
.Xr ed 1
.Sh SYNOPSIS
Finishing this section is left as a nontrivial exercise for the reader.
.Sh DESCRIPTION
Finishing this section is left as a nontrivial exercise for the reader.
.Sh AUTHORS
This program is maintained by
.An Varik Valefor
.Aq varikvalefor@aol.com .
